package service

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/usrj03l/query-pilot.git/internal/models"
)

const (
	defaultAPIURL = "https://generativelanguage.googleapis.com/v1beta/interactions"
	defaultModel  = "gemini-3.5-flash"
)

type QueryService interface {
	CreateSqlQueryResolver(sqlQueryPrompt string) (string, error)
}

type QueryResolverService struct {
	apiKey     string
	apiURL     string
	model      string
	httpClient *http.Client
}

func NewQueryResolverService(apiKey ...string) *QueryResolverService {
	key := ""
	if len(apiKey) > 0 && apiKey[0] != "" {
		key = apiKey[0]
	} else {
		key = os.Getenv("GEMINI_API_KEY")
	}

	apiURL := os.Getenv("GEMINI_API_URL")
	if apiURL == "" {
		apiURL = defaultAPIURL
	}

	model := os.Getenv("GEMINI_MODEL")
	if model == "" {
		model = defaultModel
	}

	return &QueryResolverService{
		apiKey:     key,
		apiURL:     apiURL,
		model:      model,
		httpClient: &http.Client{Timeout: 60 * time.Second},
	}
}

func (s *QueryResolverService) CreateSqlQueryResolver(sqlQueryPrompt string) (string, error) {
	sqlQueryPrompt = strings.TrimSpace(sqlQueryPrompt)
	if sqlQueryPrompt == "" {
		return "", fmt.Errorf("sql query prompt cannot be empty")
	}

	apiKey := s.apiKey
	if apiKey == "" {
		apiKey = os.Getenv("GEMINI_API_KEY")
	}
	if apiKey == "" {
		return "", fmt.Errorf("GEMINI_API_KEY is not set in environment or service configuration")
	}

	apiURL := s.apiURL
	if apiURL == "" {
		if envURL := os.Getenv("GEMINI_API_URL"); envURL != "" {
			apiURL = envURL
		} else {
			apiURL = defaultAPIURL
		}
	}

	model := s.model
	if model == "" {
		if envModel := os.Getenv("GEMINI_MODEL"); envModel != "" {
			model = envModel
		} else {
			model = defaultModel
		}
	}

	client := s.httpClient
	if client == nil {
		client = &http.Client{Timeout: 60 * time.Second}
	}

	reqPayload := models.InteractionRequest{
		Model: model,
		Input: sqlQueryPrompt,
	}

	jsonData, err := json.Marshal(reqPayload)
	if err != nil {
		return "", fmt.Errorf("failed to marshal request payload: %w", err)
	}

	req, err := http.NewRequest(http.MethodPost, apiURL, bytes.NewBuffer(jsonData))
	if err != nil {
		return "", fmt.Errorf("failed to create http request: %w", err)
	}

	req.Header.Set("x-goog-api-key", apiKey)
	req.Header.Set("Content-Type", "application/json")

	resp, err := client.Do(req)
	if err != nil {
		return "", fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("failed to read response body: %w", err)
	}

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return "", fmt.Errorf("api request failed with status code %d: %s", resp.StatusCode, string(body))
	}

	var interactionResp models.InteractionResponse
	if err := json.Unmarshal(body, &interactionResp); err != nil {
		return "", fmt.Errorf("failed to parse response json: %w", err)
	}

	var result strings.Builder
	for _, step := range interactionResp.Steps {
		if step.Type == "model_output" {
			for _, content := range step.Content {
				if content.Text != "" {
					result.WriteString(content.Text)
				}
			}
		}
	}

	output := strings.TrimSpace(result.String())
	if output == "" {
		return "", fmt.Errorf("no output generated by model in response")
	}

	return output, nil
}
